Readme review 28619
CO-CONNECT/mapping-pipeline pull request #2
Opened 2020-12-07 15:41 UTC by fierytortilla

Let me know how you feel about my reviews thus far and what you might want me to change.

2021-01-15 09:25 UTC, simon-tarr commented
Is this pull request still required @fierytortilla?

2021-01-15 11:57 UTC, fierytortilla commented
@simon-tarr I'm not really sure if it is required anymore, since so many other things has happened since I last did this pull request. I would prefer if we could discuss my proposals altogether as a team in the next Code review/retro so that we can have a good holistic conversation about what we want/don't want.

2021-01-25 10:06 UTC, py5gol commented on CONTRIBUTING.md
> +#DS- Should there be more details added to the branch naming scheme other than the sprint work item number?
The proposal is <ticket_id>-<brief description>, i.e. 29973-docker-configuration.

2021-01-25 10:14 UTC, py5gol requested changes

2021-01-25 10:14 UTC, py5gol commented on CONTRIBUTING.md
> +#DS- How will the Azure Devops work items and Git by manually linked afterwards if a commit message is not referenced?
See example above for commit messages. Branch names do not take the symbol #.

2021-01-25 10:14 UTC, py5gol commented on CONTRIBUTING.md
> +#DS- What kind of testing package or testing framework should be utilized (e.g. unittest, pytest, robot)? This should be specified.
If writing pure Python code, pytest. If Django code, then Django's testing library. If .NET, then xunit.

2021-01-25 10:14 UTC, py5gol commented on CONTRIBUTING.md
> +#DS- More information should be made available for new developers not familiar with CI techniques.
Yes, but we will add this info later.

2021-01-25 10:14 UTC, py5gol commented on README.md
> +#DS- Let's copy+paste some code from the data onboarding document to get a general description of project. Furthermore, let's also specify what goals of the project this repository seeks to achieve.
Lets add it later.

2021-01-25 10:14 UTC, py5gol commented on README.md
> +#DS- We agreed on using Python, but we should also specify what packages/frameworks we will also be using. If necessary, let's also specify an IDE program that we could all use in order to have a con
Packages go into the requirements.txt, and no need to specific IDE.

2021-02-16 16:01 UTC, closed without merging