display versions of Document and allow for new Document file upload
CO-CONNECT/mapping-pipeline pull request #32
Opened 2021-02-11 15:16 UTC by vpnu

This PR includes code for

- displaying the versions of a document
- allowing the user to upload a new version of a document
- small changes in the templates(titles and content)

2021-02-14 22:37 UTC, py5gol requested changes

2021-02-14 22:37 UTC, py5gol commented on api/mapping/forms.py
> +from mapping.models import OmopTable, OmopField, DocumentType, DataPartner,Document
Please, format the code. On PyCharm, go to Menu Code > Optimize imports and Menu Code > Reformat Code.

2021-02-14 22:37 UTC, py5gol commented on api/mapping/models.py
> +        ("Live", 'Live'),
The first item in the tuple is usually uppercase, while the second is user friendly. 
("LIVE", "live").

Also, are Live and Archived the status options on Jenny's document?

2021-02-14 22:37 UTC, py5gol commented on api/mapping/models.py
> +    status=models.CharField(max_length=20,choices=STATUS_CHOICES)
Please, define one of the options as the default option. It will also help the migrations.

2021-02-14 22:37 UTC, py5gol commented on api/mapping/templates/mapping/documentfile_list.html
> +<style>
Do we need this style? Where is it applied?

2021-02-14 22:37 UTC, py5gol commented on api/mapping/templates/mapping/upload_document_file.html
> +<h2>Upload Document</h2>
Upload new version?

2021-02-16 15:49 UTC, simon-tarr approved these changes

2021-02-16 15:56 UTC, simon-tarr approved these changes

2021-02-16 15:57 UTC, simon-tarr approved these changes

2021-02-16 23:01 UTC, py5gol approved these changes

2021-02-16 23:01 UTC, merged