added scanreport and dataset permission classes
CO-CONNECT/mapping-pipeline pull request #382
Opened 2022-02-08 15:22 UTC by Samad198

2022-02-08 15:42 UTC, dcl10 requested changes

2022-02-08 15:42 UTC, dcl10 commented on api/mapping/permissions.py
> +        """
```suggestion
        """
        Return `True` if, the dataset is 'public' and the User's ID is in the Project's members, or, the dataset is 'restricted' and the User's ID is in a project the User is a member of. 
        """
```

2022-02-08 15:42 UTC, dcl10 commented on api/mapping/permissions.py
> +            self.message = "You are not part of any projects for this dataset"
```suggestion
            self.message = "You are not a member of any projects for this dataset"
```

2022-02-08 15:42 UTC, dcl10 commented on api/mapping/permissions.py
> +        print("VISIBILITY IS", visibility)
```suggestion
```

2022-02-08 15:42 UTC, dcl10 commented on api/mapping/permissions.py
> +            self.message = "You are not part of any projects for this scan report"
```suggestion
            self.message = "You are not a member of any projects for this scan report"
```

2022-02-08 15:42 UTC, dcl10 commented on api/mapping/permissions.py
> +        Return `True` if the User's ID is in the Project's members.
```suggestion
        Return `True` if, the scan report is 'public' and the User's ID is in the Project's members, or, the scan report is 'restricted' and the User's ID is in a project the User is a member of.
```

2022-02-08 16:11 UTC, Samad198 commented
Public
<img width="498" alt="image" src="https://user-images.githubusercontent.com/38753056/153025654-9260bbb0-26d3-468b-bda0-8e060cf08259.png">

Restricted 
<img width="338" alt="image" src="https://user-images.githubusercontent.com/38753056/153028122-645bf879-8919-484a-8935-4be98ce22428.png">

2022-02-08 16:14 UTC, dcl10 approved these changes
LGTM

2022-02-09 11:30 UTC, Samad198 commented
<img width="513" alt="image" src="https://user-images.githubusercontent.com/38753056/153188840-cbc56d4a-0485-42a8-b888-8f01f7815306.png">


<img width="548" alt="image" src="https://user-images.githubusercontent.com/38753056/153191522-5cdc77e7-7faa-40dd-9469-322f8367b356.png">

2022-02-09 11:47 UTC, dcl10 approved these changes

2022-02-09 14:40 UTC, calmacx approved these changes
approved if you want to make that small change to remove commented out code and then merge

2022-02-09 14:40 UTC, calmacx commented on api/mapping/urls.py
> +    # ),
removed commented out code

2022-02-10 12:26 UTC, merged