fixed mapping json download
CO-CONNECT/mapping-pipeline pull request #425
Opened 2022-03-11 11:04 UTC by Samad198

# Changes

- Fixed broken downloading of mapping json and downloading of mapping csv caused by model changes

# Migrations

# Screenshots
- The pull request fixes the bug caused by the migration changes, but I have found that download mapping csv for 
/scanreports/40/mapping_rules/
still throws an unrelated error.
I believe it is thrown on this line inside services_rules.py with this value inside the content variable
<img width="633" alt="image" src="https://user-images.githubusercontent.com/38753056/157854921-2a12011d-610f-4dc8-ac47-ffc3fb9f615f.png">
<img width="742" alt="image" src="https://user-images.githubusercontent.com/38753056/157854993-29d36159-74b5-49e1-8fba-83e35731b278.png">

# Checks

**Important:** please complete these **before** merging.
- [ ] Run migrations, if any.
- [ ] Update `changelog.md`, including migration instructions if any.
- [ ] Run unit tests.

2022-03-11 11:09 UTC, calmacx commented
@Samad198 are you saying you wanting me to look at what is going on in `services_rules.py` ? to figure out what is still causing a crash?

2022-03-11 11:14 UTC, Samad198 commented
> @Samad198 are you saying you wanting me to look at what is going on in `services_rules.py` ? to figure out what is still causing a crash?

Yes please, i'm not really sure how the csv code works

2022-03-11 11:19 UTC, Samad198 commented
Should have included that this is the error that's thrown
<img width="962" alt="image" src="https://user-images.githubusercontent.com/38753056/157857462-773742db-86ea-4a29-98dd-f5cfbd42d883.png">

2022-03-11 12:01 UTC, spco commented
I think the issue here is that the value beginning  `SARS-COV-2` contains a comma and thus needs escaping. We have set `csv.QOUTE_NONE`, sand so it raises an `Error` as per https://docs.python.org/3/library/csv.html#csv.QUOTE_NONE .

I think in the `csv.writer` declaration you can supply `escapechar='\'`. It doesn't matter too much what escapechar we use as the CSV is only for human-readability. @calmacx do you see an issue if we do that?

2022-03-11 12:03 UTC, spco commented
Actually, perhaps I'd prefer is we didn't add `escapechar` and instead switched to using `QUOTE_MINIMAL` in place of `QUOTE_NONE`. Any objections?

2022-03-11 12:16 UTC, calmacx commented
No objections @spco  - though do we even need this csv download stuff? Was it suppose to be for NHS-D, who wanted to do their own mapping ?

2022-03-11 12:20 UTC, spco commented
As it's here I think we may as well keep it - it is not high-maintenance.

2022-03-11 16:30 UTC, spco requested changes
Just replace QUOTE_NONE with QUOTE_MINIMAL

2022-03-15 20:56 UTC, spco approved these changes

2022-03-15 20:56 UTC, merged