Allow user to Archive Datasets, add hidden field to Dataset model, di…
CO-CONNECT/mapping-pipeline pull request #460
Opened 2022-04-11 14:19 UTC by vpnu

…splay in DatasetTbl view

# Changes
- Create hidden field in Dataset Model
- Add Archive/Active button to Datasets page
- Add Filter for active/archived datasets to Datasets page

# Migrations
- Add `hidden` `BooleanField` to `Dataset`.

# Screenshots
- Page with Active/Archive filters and buttons

<img width="1260" alt="Screenshot 2022-04-11 at 15 19 21" src="https://user-images.githubusercontent.com/75254435/162759855-7dc8a12c-34e8-46ca-8da1-f5dc90b345e5.png">

# Checks

**Important:** please complete these **before** merging.
- [ ] Run migrations, if any.
- [ ] Update `changelog.md`, including migration instructions if any.
- [ ] Run unit tests.

2022-04-11 14:54 UTC, dcl10 requested changes

2022-04-13 11:55 UTC, dcl10 approved these changes
Subject to @vpnu doing the migration on dev, LGTM

2022-04-14 08:28 UTC, spco commented on react-client-app/src/components/UploadScanReport.jsx
> +            const datasets_query = await useGet(`/datasets/?data_partner=${dataPartnerId}&hidden=false`)
```suggestion
            // Show only Datasets that have this Data Partner and are no archived
            const datasets_query = await useGet(`/datasets/?data_partner=${dataPartnerId}&hidden=false`)
```
Just being a bit more explicit

2022-04-14 08:31 UTC, spco reviewed
Looks good. What are your thoughts on 55825? I think we _should_ remove mappings from consideration if their Dataset is archived, in the same way that we do with archived SRs. That is then consistent and gives probably the expected behaviour when the user just wants to archive the whole Dataset rather than having to go through all its SRs, archiving each. Agree/disagree?

2022-04-14 14:27 UTC, merged